# Generated by Django 3.2.16 on 2022-12-23 15:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Monster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        verbose_name="Name",
                    ),
                ),
                (
                    "speed",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Speed",
                    ),
                ),
                (
                    "attack",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Attack",
                    ),
                ),
                (
                    "defense",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Defense",
                    ),
                ),
                (
                    "hp",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Hp",
                    ),
                ),
                (
                    "imageUrl",
                    models.URLField(
                        validators=[django.core.validators.URLValidator()],
                        verbose_name="Image URL",
                    ),
                ),
            ],
            options={
                "verbose_name": "Monster",
                "verbose_name_plural": "Monsters",
                "ordering": ["name", "-attack"],
            },
        ),
    ]
