# Generated by Django 3.2.16 on 2022-12-26 21:11

from django.db import migrations


def load_initial_data(apps, schema_editor):
    # get our model
    # get_model(appname, modelname)
    initial_data = [
        {
            "id": 1,
            "name": "Dead Unicorn",
            "imageUrl": "https://fsl-assessment-public-files.s3.amazonaws.com/assessment-cc-01/dead-unicorn.png",
            "attack": 60,
            "defense": 40,
            "hp": 10,
            "speed": 80,
        },
        {
            "id": 2,
            "name": "Old Shark",
            "imageUrl": "https://fsl-assessment-public-files.s3.amazonaws.com/assessment-cc-01/old-shark.png",
            "attack": 50,
            "defense": 20,
            "hp": 80,
            "speed": 90,
        },
        {
            "id": 3,
            "name": "Red Dragon",
            "imageUrl": "https://fsl-assessment-public-files.s3.amazonaws.com/assessment-cc-01/red-dragon.png",
            "attack": 90,
            "defense": 80,
            "hp": 90,
            "speed": 70,
        },
        {
            "id": 4,
            "name": "Robot Bear",
            "imageUrl": "https://fsl-assessment-public-files.s3.amazonaws.com/assessment-cc-01/robot-bear.png",
            "attack": 50,
            "defense": 40,
            "hp": 80,
            "speed": 60,
        },
        {
            "id": 5,
            "name": "Angry Snake",
            "imageUrl": "https://fsl-assessment-public-files.s3.amazonaws.com/assessment-cc-01/angry-snake.png",
            "attack": 80,
            "defense": 20,
            "hp": 70,
            "speed": 80,
        },
    ]

    monster_model = apps.get_model("monster", "Monster")

    [monster_model(**row).save() for row in initial_data]


class Migration(migrations.Migration):
    dependencies = [
        ("monster", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(load_initial_data),
    ]
